# Generated by Django 3.1.2 on 2021-02-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('plage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.plage')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.salle')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.ue')),
            ],
        ),
    ]
