# Generated by Django 3.1.2 on 2021-02-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveillance', '0003_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.exam')),
                ('surveillant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.surveillant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
