# Generated by Django 3.1.4 on 2021-02-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_controler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='salle',
        ),
        migrations.AddField(
            model_name='controler',
            name='salle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='surveillance.salle'),
            preserve_default=False,
        ),
    ]
