# Generated by Django 3.1.2 on 2021-03-03 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveillance', '0005_auto_20210228_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_control', to='surveillance.exam'),
        ),
        migrations.AlterField(
            model_name='controler',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_control', to='surveillance.salle'),
        ),
        migrations.AlterField(
            model_name='controler',
            name='surveillant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surv_control', to='surveillance.surveillant'),
        ),
        migrations.AlterField(
            model_name='controler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_control', to=settings.AUTH_USER_MODEL),
        ),
    ]
