# Generated by Django 3.1.2 on 2021-03-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0006_auto_20210304_1421'),
        ('surveillance', '0006_auto_20210303_1652'),
    ]

    operations = [
    ]
