# Generated by Django 3.1.2 on 2021-03-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveillance', '0007_merge_20210304_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_control', to=settings.AUTH_USER_MODEL),
        ),
    ]
