# Generated by Django 3.1.2 on 2021-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0008_auto_20210312_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
